logging:
  level:
    com:
      bryanobana: DEBUG

scheduling:
  cron: "0 0 1 1 1 *"
  #cron: "0 46 00 7 9 *" # Used for testing

fan:
  speed:
    max: 3
    min: 0

airconditioner:
  temperature:
    max: 24
    min: 18
